[project]
name = "cai"
version = "0.0.0.1"
description = "Hilfsprogramm zum Erstellen der Freitexte eines Pflegegutachtens"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "customtkinter>=5.2.2",
]
